---
# Services will be auto-discovered from Docker labels
# You can manually add services here if needed

# Example of manual service entry:
# - Network & Infrastructure:
#     - Pi-hole:
#         href: http://{{HOMEPAGE_VAR_PI_IP}}:8080/admin
#         description: Network-wide ad blocking
#         icon: pi-hole.png
#         server: my-docker
#         container: pihole
#         widget:
#           type: pihole
#           url: http://pihole:80
#           key: {{HOMEPAGE_VAR_PIHOLE_KEY}}
